---
apiVersion: v1
kind: Service
metadata:
  name: app-be-user
spec:
  selector:
    app: app-be-user
  ports:
    - protocol: "TCP"
      port: 3001
      targetPort: 3001
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-be-user
spec:
  selector:
    matchLabels:
      app: app-be-user
  replicas: 1
  template:
    metadata:
      labels:
        app: app-be-user
    spec:
      containers:
        - name: app-be-user
          image: app-be-user:v1.0.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: NEST_APP_NAME
              value: "app-be-user"
            - name: NEST_API_PORT
              value: "3001"
            - name: NEST_MQ_CONNECTION_STRING
              value: "kubemq-cluster-grpc.kubemq:50000"
            - name: NEST_MONGODB_CONNECTION_STRING
              value: "mongodb+srv://attila:Idq2fdKRxWMceDx4@cluster0.ml4i0.mongodb.net/nestjs-practise?retryWrites=true&w=majority"
